# Site settings
title: My Projects
email: asher.trockman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Explorations in programming, computer science, and math (listed according to frequency).
  Learning by doing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashertrockman.github.io/" # the base hostname & protocol for your site
github_username:  ashertrockman
twitter_username: ashertrockman

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
