# Site settings
title: My Projects
email: asher@trockman.net
description: > # this means to ignore newlines until "baseurl:"
  Explorations in programming, computer science, and math (listed according to frequency).
  Learning by doing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  ashertrockman

# Build settings
markdown: kramdown
